name: CI

on:
  pull_request:
  push:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly, beta, stable]

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: check async-std
      run: cargo check --workspace --all-targets --no-default-features --features runtime-async-std

    - name: check tokio
      run: cargo check --workspace --all-targets --no-default-features --features runtime-tokio

    - name: check async-std examples
      working-directory: examples
      run: cargo check --workspace --all-targets --no-default-features --features runtime-async-std

    - name: check tokio examples
      working-directory: examples
      run: cargo check --workspace --all-targets --no-default-features --features runtime-tokio

    - name: tests
      run: cargo test --workspace

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

    - name: fmt
      run: cargo fmt --all -- --check

    - name: Docs
      run: cargo doc

  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install rust
        run: rustup update beta && rustup default beta
      - name: Install clippy
        run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all
